# Site settings
name: 'The Hallway'
description: "Chris Vannoy's thoughts on code, analytics, careers, pop culture and raising kids on the Autism Spectrum."

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://blog.chrisvannoy.com' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          true
paginate:            8
paginate_path:       page/:num/

array: []

author:
    name: 'Chris Vannoy'
    email: 'chris@chrisvannoy.com'
    uri: 'https://github.com/dummied'

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: false
        # Meta
        show_tags: true
        show_categories: false
        # Social
        share_buttons: true
        disqus: false
        type: 'post'
        status: 'draft'
        categories: []
        tags: []
        meta:
          image: ''
          _publicize_twitter_user: "@chris_vannoy"
        author:
          login: "chris_vannoy"
          email: "chris@chrisvannoy.com"
          display_name: "Chris Vannoy"
          first_name: "Chris"
          last_name: "Vannoy"


gems:
    - jekyll-feed
    - jekyll-sitemap

tag_page_layout: tag
tag_page_dir: tag
tag_permalink_style: pretty
